name: Build Debian Package

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive version from ref
        id: ver
        run: |
          REF="${GITHUB_REF_NAME}"
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VER="${REF#v}"
          else
            VER="0.0.0+${GITHUB_RUN_NUMBER}"
          fi
          echo "VER=$VER" >> $GITHUB_ENV
          echo "version=$VER" >> $GITHUB_OUTPUT

      - name: Install packaging toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts debhelper dpkg-dev fakeroot

      - name: Build with debian/*
        if: ${{ hashFiles('debian/control') != '' }}
        env:
          VER: ${{ env.VER }}
        run: |
          export DEBFULLNAME="CI"
          export DEBEMAIL="ci@example.invalid"
          dch -v "${VER}-1" -b "Automated build for ${GITHUB_SHA::7}"
          dch -r ""
          dpkg-buildpackage -us -uc -b

      - name: Build (fallback via fpm)
        if: ${{ hashFiles('debian/control') == '' }}
        env:
          VER: ${{ env.VER }}
        run: |
          sudo apt-get install -y ruby ruby-dev rubygems
          sudo gem install --no-document fpm
          mkdir -p pkg/usr/local/bin
          cp RUBookmatedownloader.py pkg/usr/local/bin/RUBookmatedownloader
          fpm -s dir -t deb \
            -n rubookmatedownloader \
            -v "${VER}" \
            --description "RUBookmatedownloader" \
            --license "MIT" \
            --prefix / \
            -C pkg \
            usr/local/bin/RUBookmatedownloader

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: rubookmatedownloader-${{ env.VER }}-deb
          path: |
            *.deb
            ../*.deb
